add clean-dir.js and remove rimraf
ioBroker/adapter-dev pull request #273
Opened 2024-12-26 20:38 UTC by ticaki

Als Ersatz für rimraf

2024-12-27 10:13 UTC, AlCalzone commented
Please mention the new functionality in the Readme

2024-12-27 22:23 UTC, mcm1957 commented
Isn't this functionality provided by iobroker/build-tools anyway?
https://github.com/ioBroker/build-tools#deletefoldersrecursive

build-tools is used for react - at least for new projects. Maybe it should be used for Typescript too.

I suggest to discuss with @GermanBluefox

2025-01-02 16:02 UTC, Apollon77 commented
Yes but these tools are JS methods ... here we have CLI ... thats fine.
@ticaki culd you please rebase? Thank you

2025-01-02 17:45 UTC, mcm1957 commented
@Apollon77 
OK - please let me know when this change is available as an update.

As rimraf needs to be removed from adapter package.json it would make sense to add a suggestion to iobroker adapter checker after a new version of adapter-dev is available to (eventually) replace rimraf.

@ticaki 
Please provide a PR for create-adapter too and remove rimraf and adapter build scripts wehre appropiate as otherwise new repos will still be created using rimraf

2025-01-02 20:51 UTC, AlCalzone requested changes
This new CLI "tool" should be documented like the existing ones, for example:
https://github.com/ioBroker/adapter-dev?tab=readme-ov-file#compile-adapter-files

2025-01-02 20:51 UTC, AlCalzone commented on bin/clean-dir.js
> + * "prebuild": "node ./node_modules/@iobroker/adapter-dev/bin/clean-dir.js ./build",
`clean-dir.js` should be added to `adapter-dev`s package.json `bin`, like the existing tools. That way the call on the developer side would look like this:
```suggestion
 * "prebuild": "clean-dir ./build",
```

2025-01-03 07:13 UTC, ticaki commented
@mcm1957 
I'll take a look at this

@AlCalzone 
Thanks for pointing this out, I have now understood how it works.

2025-02-21 10:35 UTC, merged